### ISSUE TITLE
Changing font programmatically which is not shown in the rendered video

### ISSUE THREAD

**Issue by Muhammad-Ashik** [arthurdenner/remotion-lottie-test#12] opened 2022-01-20 13:15 UTC
I am changing the fonts programmatically and it is working perfectly in Player. But after rendering the video that I am getting from the remotion, where the changed font is not showing instead getting a default font. 

**Here is a image for the Player:**

![font changed in player](https://user-images.githubusercontent.com/38232006/150346261-937a4eef-830c-4fb6-8c64-581483c8cc8f.JPG)

**After rendered:**

![not changed](https://user-images.githubusercontent.com/38232006/150346341-8589d923-51fc-4790-91fb-87f75928bf8a.JPG)

**Comment by arthurdenner** [comment] 2022-01-20 16:24
Hi @Muhammad-Ashik! 👋🏽 

Are you importing the font in one of the [documented ways](https://www.remotion.dev/docs/fonts)?
If so, a reproducible example is needed - a CodeSandbox won't work here since it's regarding the render step.

**Comment by Muhammad-Ashik** [comment] 2022-01-20 17:24
Where should I import the fonts. In Lottie Components or in the App? Could you please give a example?

**Comment by arthurdenner** [comment] 2022-01-20 17:50
I think the preferred place would be inside the top-level component that needs it, so it's loaded "as soon as possible".

If you're using the font throughout the whole video, it can be the component used as Composition.
If you're using only inside a piece of the video, it can be that component. It depends on your use case.

Here is an example for loading local fonts with `staticFile`: [link](https://github.com/remotion-dev/remotion/blob/main/packages/example/src/Fonts/index.tsx). I couldn't find a code example but you can also follow [this method](https://www.remotion.dev/docs/fonts#google-fonts) and have a CSS file declaring the font-family and import the CSS file when needed.

**Comment by arthurdenner** [comment] 2022-01-31 08:08
@Muhammad-Ashik, did you manage to get the font working correctly?

**Comment by arthurdenner** [comment] 2022-02-02 18:24
Closing as agreed with Muhammad in another chat. Will be reopened if needed.

**Closed as completed by arthurdenner** 2022-02-02 18:24 UTC
